apiVersion: 1

deleteDatasources:
  - name: MYINFLUX
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: ${GRAFANA_IDB_TOKEN}
    jsonData:
      version: Flux
      organization: ${GRAFANA_IDB_ORG}
      defaultBucket: ${GRAFANA_IDB_BUCKET}
      tlsSkipVerify: true
